pipeline:
  test:
    image: golang:latest
    commands:
      - export GOPATH=/drone
      - go get ./... github.com/letsencrypt/pebble/cmd/pebble
      - go install ./... github.com/letsencrypt/pebble/cmd/pebble
      - go test -tags integration ./...
